- id: validate_copyright
  name: validate_copyright
  description: "Validate Copyright"
  entry: validate_copyright
  files: '\.(js|ts|py|md)$'
  language: python
  require_serial: true

- id: clean_customized_doctypes
  name: clean_customized_doctypes
  description: "Clean customized doctypes"
  entry: clean_customized_doctypes
  language: python
  require_serial: true

- id: validate_javascript_dependencies
  name: validate_javascript_dependencies
  description: "Examine package.json across the installed apps on the site to detect any version mismatches"
  entry: validate_javascript_dependencies
  language: python
  require_serial: true

- id: validate_python_dependencies
  name: validate_python_dependencies
  description: "Examine pyptoject.toml across the installed apps on the site to detect any version mismatches"
  entry: validate_python_dependencies
  language: python
  require_serial: true

- id: validate_customizations
  name: validate_customizations
  description: "Validate Customizations"
  entry: validate_customizations
  language: python
  require_serial: true

- id: update_pre_commit_config
  name: update_pre_commit_config
  description: "Update test_utils pre-commit config to latest"
  entry: update_pre_commit_config
  language: python
  require_serial: true

- id: mypy
  name: mypy
  description: "Check for type hints"
  entry: mypy
  language: python
  types: [python]
  exclude: ^tests/
  args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]

- id: track_overrides
  name: track_overrides
  description: "Track overrides"
  entry: track_overrides
  language: python
  require_serial: true

- id: add_translations
  name: add_translations
  description: "Get untranslated strings in app and translate them to the language specified"
  entry: add_translations
  language: python
  require_serial: true

- id: sql_docstring_formatter
  name: sql_docstring_formatter
  description: "Format SQL statements in Python docstrings"
  entry: sql_docstring_formatter
  language: python
  types: [python]
  additional_dependencies: ['sqlglot>=25.0.0']
  args: ['--dialect', 'mysql']

- id: sql_registry
  name: SQL Registry
  description: "Register SQL operations for tracking and potential rewriting"
  entry: sql_registration
  language: python
  files: '\.py$'
  require_serial: true
  additional_dependencies: ['sqlglot>=25.0.0']
  args: ['scan']

- id: sql_rewriter
  name: SQL Rewriter CLI
  description: "Interactive tool for converting SQL calls to Query Builder"
  entry: sql_registration
  language: python
  pass_filenames: false
  always_run: true
  require_serial: true
  additional_dependencies: ['sqlglot>=25.0.0']
  
- id: bylines
  name: bylines
  description: "Add byline <div> in markdown files with authors from git history"
  entry: bylines
  language: python
  require_serial: true

- id: patch_linters
  name: patch_linters
  description: "Validate patches.txt matches patch files for ERPNext apps"
  entry: patch_linters
  language: python
  require_serial: true
  pass_filenames: false
  args: []

- id: validate_frappe_dependencies
  name: validate_frappe_dependencies
  description: "Validate that pyproject.toml declares bounded frappe/erpnext dependencies under [tool.bench.frappe-dependencies]"
  entry: validate_frappe_dependencies
  language: python
  always_run: true
  pass_filenames: false
  require_serial: true
