- id: validate_copyright
  name: validate_copyright
  description: "Validate Copyright"
  entry: validate_copyright
  files: '\.(js|ts|py|md)$'
  language: python
  require_serial: true

- id: clean_customized_doctypes
  name: clean_customized_doctypes
  description: "Clean customized doctypes"
  entry: clean_customized_doctypes
  language: python
  require_serial: true

- id: validate_javascript_dependencies
  name: validate_javascript_dependencies
  description: "Examine package.json across the installed apps on the site to detect any version mismatches"
  entry: validate_javascript_dependencies
  language: python
  require_serial: true

- id: validate_python_dependencies
  name: validate_python_dependencies
  description: "Examine pyptoject.toml across the installed apps on the site to detect any version mismatches"
  entry: validate_python_dependencies
  language: python
  require_serial: true
